### ISSUE TITLE
Lesson 3: FundMe minimumUSD bug

### ISSUE THREAD

**Issue by shahronak** [PatrickAlphaC/fund_me#11]
Thanks for putting these courses together! They've been really helpful in my progress to building decentralized applications. 

I think I may have found a bug in Lesson 3 for the FundMe exercise. When trying to specify a minimum $50 USD funding amount, it should take in to account the current price of ETH for the conversion. 

Currently, line 20 is:
`uint256 minimumUSD = 50 * 10 ** 18;`

I think this should be adjusted to 
`uint256 minimumUSD = (50 / getPrice()) * 10 ** 18;`

**Comment by shahronak** [comment]
PR for this issue: https://github.com/PatrickAlphaC/fund_me/pull/12

**Comment by jerlam06** [comment]
Hi there. I was also stuck on the conversions of Lesson 3. And I am still stuck, even though I think I found out the formula.
So, here is my formula that I think is right: 
`uint256 minimumUSD = 50 * (10 ** 9);`

Here is my code with comments that helped me a lot to understand.

```
    function fund() public payable {
        uint256 minimumUSD = 50 * (10 ** 9); // In USD denominated in Gwei
        require(getConversionRate(msg.value) >= minimumUSD, "You need to spend more ETH!");
        
         // msg.value is in Wei but we want it in Gwei so: msg.value / 10 ** 9
        require(getConversionRate(msg.value / 10 ** 9) >= minimumUSD, "You need to spend more ETH!");
        
        addressToAmountFunded[msg.sender] += msg.value;
    }

    function getVersion() public view returns (uint256) {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(0x8A753747A1Fa494EC906cE90E9f37563A8AF630e);
        return priceFeed.version();
    }

    // Returns the price of 1 ETH in USD denominated in Wei
    function getPrice() public view returns (uint256) {
        AggregatorV3Interface priceFeed = AggregatorV3Interface(0x8A753747A1Fa494EC906cE90E9f37563A8AF630e);
        (,int256 price,,,) = priceFeed.latestRoundData();

        // Price is in dollar denominated in Wei, without trailling zeros. Ex: 382659433135
        // Multiplied by 10000000000 to get the 10 missing zeros: 3826594331350000000000 and get the price "in Wei"
        return uint256(price * 10000000000);
    }

    // 1000000000000000000 Wei or 1000000000 Gwei or 1 Eth
    function getConversionRate(uint256 gweiAmount) public view returns (uint256) {
        uint256 ethPriceInWei = getPrice();
        uint256 ethAmountInUsd = (ethPriceInWei * gweiAmount) / 1000000000000000000;

        // 1 Eth or 1000000000 Gwei returns => 3862103280630
        // 3862103280630 / 1000000000 Gwei = 3862.10328063 USD

        return ethAmountInUsd;
    }
```

Basically, getConversionRate() will return: **x USD * 10 ** 9**.
So right now getConversionRate(1000000000 Gwei) returns: **3826594331350 which is 3826.594331350 * 10 ** 9 => 3826 USD being the price for 1 ETH (1000000000  Gwei)**.

That being said, **50 * 10 ** 9** should now make sense.
**=> required(3826.59433135 * 10 ** 9 >= 50 * 10 ** 9)**

Whereas your formula returns the value of 50 USD in ETH => 0.013066449085121676 ETH at the time of writing these lines.

BUT, the problem is even though the comparison is right (I checked it on calculator), the payment is still passed successfully even though the required() is false. 
Is my reasoning wrong?

EDIT: So I figured out what was the issue, the msg.value is in Wei but my getConversionRate() function needs Gwei.
So I just needed that => `require(getConversionRate(msg.value / 10 ** 9) >= minimumUSD, "You need to spend more ETH!");`

**Comment by PatrickAlphaC** [comment]
Yep! You got it!

I'm trying to make this clearer in later tutorials.
