### ISSUE TITLE
Divide instead of multiply for getting right etherium price.

### ISSUE THREAD

**Issue by hishamudeen** [PatrickAlphaC/fund_me#8]
Line number 34
 return uint256(answer * 100000000); 
to
 return uint256(answer / 100000000);

and replace
Line 40
uint256 ethAmountInUsd = (ethPrice * ethAmount) / 1000000000000000000;
to
uint256 ethAmountInUsd = (ethPrice * ethAmount) ;

**Comment by PatrickAlphaC** [comment]
Why? Are you not getting the correct price as is?

**Comment by RID71K** [comment]
when using those line it shows gas estimation failed even after giving the right amount of wei

**Comment by louisamira** [comment]
I think people are running into the same error I did at first, which is you're trying to "fund" by adding wei in the "value" amount _before you deploy_. you don't need to fund in order to deploy, you only need to insert a value when you're going down to start interacting with the "fund" button

I bet this is also the error the other commenters on this chapter were running into as well. hence trying to change the minimumusd thresholds in order to get it to go through

**Comment by PatrickAlphaC** [comment]
I'm a bit confused... what's the issue?

**Comment by louisamira** [comment]
People never successfully deploy the contract, because they're trying to "fund" (i.e. add "value") it with some amount. You don't actually need to fund anything (just click deploy and leave 0 for Value), and then after it's successfully funded you can go interact with the new funding button down below. 

The errors you get in the terminal leave everyone to believe that we're not funding it with enough. When in reality, the check for "did you send >$50 worth of ETH" doesn't even matter until after the contract is deployed. At 3:06:16 you deploy with 0 "value" and click deploy. The fund button doesn't appear until later on.

To recreate, try to add something like 2 ETH in value and click deploy. Clearly 2 ETH > $50, but the error messages don't make that easy to understand.

**Comment by PatrickAlphaC** [comment]
ooo I see. 

Ok closing this issue for now. Do you think we should put some copy somewhere telling people they don't need to use ETH to deploy?

**Comment by PatrickAlphaC** [comment]
Perhaps... what do you think? Could you open a pull request for what you have in mind?
